# This is a basic workflow to help you get started with Actions

name: asa.unittest.build
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pester-test:
    name: Pester test
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Perform a Pester test
        shell: pwsh
        run: |
          $PesterResults = Invoke-Pester -Path .\asa.unittest.tests\Get-AutRunResult.Tests.ps1 -Show Fails -PassThru
          If ($PesterResults.FailedCount -ne 0) {
            Write-Error "Pester run : $($PesterResults.FailedCount) errors on $($PesterResults.TotalCount) total tests" -ErrorAction Stop
          }